"""initial schema

Revision ID: 60c64333c651
Revises:
Create Date: 2026-09-02 22:02:10.304609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60c64333c651'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('renter', 'landlord', 'admin', name='userrole'), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('phone_verified', sa.Boolean(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('bank_name', sa.String(), nullable=True),
    sa.Column('bank_code', sa.String(), nullable=True),
    sa.Column('bank_account_number', sa.String(), nullable=True),
    sa.Column('bank_account_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('landlord_verifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('unverified', 'pending', 'verified', 'failed', name='verificationstatus'), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('ownership_proof_url', sa.String(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('listings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('landlord_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('photos', sa.JSON(), nullable=True),
    sa.Column('rent_amount_ngn', sa.Integer(), nullable=False),
    sa.Column('rent_duration_months', sa.Integer(), nullable=False),
    sa.Column('agreement_fee_ngn', sa.Integer(), nullable=False),
    sa.Column('area', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('ownership_doc_url', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('pending_review', 'live', 'rejected', 'rented', 'expired', name='listingstatus'), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['landlord_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listings_landlord_id'), 'listings', ['landlord_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('rent_payment', 'additional_listing_fee', name='transactiontype'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'success', 'failed', name='transactionstatus'), nullable=False),
    sa.Column('amount_ngn', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('provider_reference', sa.String(), nullable=True),
    sa.Column('raw_response', sa.JSON(), nullable=True),
    sa.Column('related_listing_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['related_listing_id'], ['listings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    op.create_table('availability_requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('listing_id', sa.String(), nullable=False),
    sa.Column('renter_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'rejected', name='availabilitystatus'), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by_admin_id', sa.String(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('landlord_email_sent_at', sa.DateTime(), nullable=True),
    sa.Column('landlord_sms_sent_at', sa.DateTime(), nullable=True),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.ForeignKeyConstraint(['renter_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_availability_requests_listing_id'), 'availability_requests', ['listing_id'], unique=False)
    op.create_index(op.f('ix_availability_requests_renter_id'), 'availability_requests', ['renter_id'], unique=False)
    op.create_table('rent_payments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('renter_id', sa.String(), nullable=False),
    sa.Column('listing_id', sa.String(), nullable=False),
    sa.Column('availability_request_id', sa.String(), nullable=True),
    sa.Column('rent_amount_ngn', sa.Integer(), nullable=False),
    sa.Column('rent_duration_months', sa.Integer(), nullable=False),
    sa.Column('payment_reference', sa.String(), nullable=True),
    sa.Column('agreement_fee_ngn', sa.Integer(), nullable=False),
    sa.Column('total_paid_ngn', sa.Integer(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('active', 'ended', name='rentpaymentstatus'), nullable=False),
    sa.Column('reminder_1m_sent_at', sa.DateTime(), nullable=True),
    sa.Column('reminder_2w_sent_at', sa.DateTime(), nullable=True),
    sa.Column('commission_ngn', sa.Integer(), nullable=False),
    sa.Column('landlord_payout_ngn', sa.Integer(), nullable=False),
    sa.Column('payout_status', sa.Enum('awaiting_payout', 'paid_out', name='payoutstatus'), nullable=False),
    sa.Column('payout_reference', sa.String(), nullable=True),
    sa.Column('payout_paid_at', sa.DateTime(), nullable=True),
    sa.Column('is_renewal', sa.Boolean(), nullable=False),
    sa.Column('inspection_confirmed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['availability_request_id'], ['availability_requests.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.ForeignKeyConstraint(['renter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rent_payments_listing_id'), 'rent_payments', ['listing_id'], unique=False)
    op.create_index(op.f('ix_rent_payments_renter_id'), 'rent_payments', ['renter_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('rent_payment_id', sa.String(), nullable=False),
    sa.Column('sender_id', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rent_payment_id'], ['rent_payments.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_rent_payment_id'), 'chat_messages', ['rent_payment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_messages_rent_payment_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_rent_payments_renter_id'), table_name='rent_payments')
    op.drop_index(op.f('ix_rent_payments_listing_id'), table_name='rent_payments')
    op.drop_table('rent_payments')
    op.drop_index(op.f('ix_availability_requests_renter_id'), table_name='availability_requests')
    op.drop_index(op.f('ix_availability_requests_listing_id'), table_name='availability_requests')
    op.drop_table('availability_requests')
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_listings_landlord_id'), table_name='listings')
    op.drop_table('listings')
    op.drop_table('landlord_verifications')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
